#
# Copyright (c) 2009 Jose F Nieves
#
# See LICENSE
#
# $Id$
#

SUBDIRS = lib manager qrunner spooler monitor

all:
	for dir in ${SUBDIRS}; do \
	(cd $$dir; ${MAKE}) \
	done

install:
	for dir in ${SUBDIRS}; do \
	(cd $$dir; ${MAKE} install) \
	done

clean:
	rm -f *~
	for dir in ${SUBDIRS}; do \
	(cd $$dir; ${MAKE} clean) \
	done
